import Link from "next/link";
import { APP_NAME, ORG_NAME, CONTACT_EMAIL } from "@/lib/site-config";

export const metadata = {
  title: `Privacy Policy — ${APP_NAME}`,
  description: `How ${ORG_NAME} handles candidate data in the ${APP_NAME} hiring tool.`,
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <main className="mx-auto max-w-3xl px-6 py-16 prose prose-slate">
        <p className="text-xs uppercase tracking-wide text-slate-400 mb-2">
          Last updated: 2026-04-30
        </p>
        <h1>Privacy Policy</h1>

        <p>
          This page explains how {ORG_NAME} (&ldquo;we&rdquo;) handles personal
          data submitted through the {APP_NAME} hiring tool. If you applied for a
          role through this site, this policy describes what we collect and why.
        </p>

        <h2>What we collect</h2>
        <ul>
          <li>Your name and email address (provided when an invite is created)</li>
          <li>Your written answers to the assessment questions</li>
          <li>Your CV / resume if you upload one</li>
          <li>
            Engagement signals: when you opened the link, how long the
            assessment took, which sections you completed, and basic device
            metadata (browser, IP address) used for security
          </li>
          <li>
            AI-assisted scoring of your written answers, generated by
            Anthropic&rsquo;s Claude API. The model is given your answers
            against the role&rsquo;s rubric and returns a structured score
            and notes for our hiring team
          </li>
        </ul>

        <h2>What we do with it</h2>
        <p>
          We use this data only to assess your suitability for the role you
          applied for, and to share that assessment with our hiring team.
          We do not sell your data. We do not use it for advertising. We do
          not share it with third parties other than our processors below.
        </p>

        <h2>Processors</h2>
        <ul>
          <li>
            <strong>Anthropic</strong> — your written answers are sent to
            Anthropic&rsquo;s Claude API for scoring. Anthropic states that
            API data is not used to train its models. See{" "}
            <a href="https://www.anthropic.com/legal/privacy" rel="noopener noreferrer">
              Anthropic&rsquo;s privacy policy
            </a>
            .
          </li>
          <li>
            <strong>Hosting</strong> — application data is stored on
            infrastructure controlled by {ORG_NAME}. Review your deployment&rsquo;s
            hosting and backup arrangements and describe them here.
          </li>
        </ul>

        <h2>How long we keep it</h2>
        <p>
          We keep your application data for the duration of the hiring
          process plus a reasonable archive period (typically up to 12
          months) so we can refer back to past applications. After that, the
          data is deleted on request or during routine cleanup.
        </p>

        <h2>Your rights</h2>
        <p>
          You can ask us at any time to:
        </p>
        <ul>
          <li>Send you a copy of the data we hold about you</li>
          <li>Delete your data</li>
          <li>Correct anything we have on file that is wrong</li>
        </ul>
        <p>
          Email{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>{" "}
          and we will action it within 14 days.
        </p>

        <h2>Security</h2>
        <p>
          The site is served over HTTPS. Admin access is restricted to a
          short allowlist of staff emails. Your assessment link contains
          a one-time token that is unique to you — please do not share it.
        </p>

        <h2>Contact</h2>
        <p>
          For any privacy questions, email{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          .
        </p>

        <p className="text-xs text-slate-500 mt-12 border-t border-slate-200 pt-4">
          <Link href="/terms">Terms of Use</Link>
        </p>
      </main>
    </div>
  );
}
