import Link from "next/link";
import { APP_NAME, ORG_NAME, CONTACT_EMAIL } from "@/lib/site-config";

export const metadata = {
  title: `Terms of Use — ${APP_NAME}`,
  description: `Terms governing use of the ${APP_NAME} hiring tool.`,
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <main className="mx-auto max-w-3xl px-6 py-16 prose prose-slate">
        <p className="text-xs uppercase tracking-wide text-slate-400 mb-2">
          Last updated: 2026-04-30
        </p>
        <h1>Terms of Use</h1>

        <p>
          These terms govern your use of the {APP_NAME} hiring tool. By
          submitting an application through this site you agree to the points
          below.
        </p>

        <h2>Honest answers</h2>
        <p>
          The assessment is intended to measure your own thinking. Submitting
          answers that were primarily generated by an AI tool, or copied from
          another source without acknowledgement, is grounds for withdrawing
          your application.
        </p>

        <h2>Your invite link</h2>
        <p>
          The link you received is unique to you and expires on the date
          shown. Please do not share it. If you need a fresh link, email{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          .
        </p>

        <h2>What happens to your submission</h2>
        <p>
          Your written answers are reviewed by the {ORG_NAME} hiring team
          alongside AI-assisted scoring. We will get back to you with a decision
          in a reasonable timeframe. See the{" "}
          <Link href="/privacy">privacy policy</Link> for details on data
          handling.
        </p>

        <h2>Service availability</h2>
        <p>
          We aim to keep the site available but we do not promise uptime. If
          the site is down when you are trying to submit, your progress is
          saved and you can return later.
        </p>

        <h2>No employment contract</h2>
        <p>
          Submitting an application through this site does not create any
          employment relationship or offer of employment. Any offer will be
          made separately in writing.
        </p>

        <h2>Changes to these terms</h2>
        <p>
          We may update these terms occasionally. The &ldquo;last
          updated&rdquo; date at the top of the page reflects the current
          version.
        </p>

        <h2>Contact</h2>
        <p>
          Questions:{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          .
        </p>

        <p className="text-xs text-slate-500 mt-12 border-t border-slate-200 pt-4">
          <Link href="/privacy">Privacy Policy</Link>
        </p>
      </main>
    </div>
  );
}
